version: '3'

services:
  postgres:
    build: ./postgres
    ports:
      - "5431:5432"
    environment:
      POSTGRES_DB: covid
      POSTGRES_USER: covid
      POSTGRES_PASSWORD: covid
  frontend:
    build: ./frontend
    environment:
      PORT: 3030
    depends_on:
      - "hasura"
    volumes:
      - ./frontend:/frontend:cached
      - /frontend/node_modules
    ports:
      - "3030:80"
  hasura:
    image: hasura/graphql-engine:v1.1.0.cli-migrations
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - "postgres"
    volumes:
      - ./hasura/migrations:/hasura-migrations
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://covid:covid@postgres:5432/covid
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey